### PR TITLE
Replace custom error type with std::io::Error.

### PR DESCRIPTION
**Pull request by de-vri-es**
Since we were talking about backwards incompatible changes, I think it would be nice to use `std::io::Error` directly instead of a custom error type.

I believe this has the following advantages:
* Since this is a low level library doing only a single operation per call, I believe it's best for the error to indicate *how* the operation failed, but not the details of *which* operation failed. That allows the user application more freedom in how the error is reported while still using the `Display` implementation of the error.
* It's also what `std` does, so error handling code in user applications can do the same thing for `std` calls as for `memfd` calls.
* The old error type encodes failure for memfd creation, adding seals and getting seals in the same type. As a result, as far as the type system is concerned, `memfd.add_seal()` could fail with `Error::GetSeals`.

One potential downside:
* A name containing null-bytes is now flattened into an `std::io::Error` with `ErrorKind::InvalidInput`, which makes it harder to handle specifically in code. I believe this is a very rare use case though: most names will often be hardcoded, and even when they're not, null bytes in names are still unlikely. Also: a name that is too long is already reported as invalid input by the OS itself.

### CODE REVIEW

**Comment by nagisa** [comment]
In my experience as libraries expand, even if they are just a thin wrapper around some OS functionality, they inevitably gain new and exciting error cases that `io::Error` is not very good at accommodating.

>  believe it's best for the error to indicate how the operation failed, but not the details of which operation failed.

It is actually doing the former! It just happens to also be the same thing as latter. As in, no matter how you look at

```
let fd = memfd_create(name_ptr, flags);
```

the only thing you can say about this when it fails that it was a `memfd_create` that failed, hence `Error::Create`. There's already another failure mode in that function, which I guess can still be shoved into `io::Error` with some effort, but were there _another_ fallible operation in that function in the future, you'd suddenly start utilizing downcasting of the contained error type to make any sense of the errors that come out.

 We could look into making some of the variants “transparent” for the error display purposes, though.

**Comment by nagisa** [comment]
Another option I could see is using specific newtypes (enums with a single variant) over `io::Error` for each different function.

So for instance:

```rust
enum GetSealsError {
    GetSealsFnctl(std::io::Error)
}

fn file_get_seals(fp: &fs::File) -> Result<u64, GetSealsError> { ... }

enum SetSealsError {
    SetSealsFnctl(std::io::Error)
}

fn file_set_seals(fp: &fs::File) -> Result<u64, SetSealsError> { ... }

/* etc */
```

**Comment by de-vri-es** [comment]
> It is actually doing the former! It just happens to also be the same thing as latter. As in, no matter how you look at
> 
> ```
> let fd = memfd_create(name_ptr, flags);
> ```
> 
> the only thing you can say about this when it fails that it was a `memfd_create` that failed, hence `Error::Create`.

I don't think this is true. `memfd_create` can fail in multiple ways: the name can be too long, the flags can include invalid combinations, the process may have hit the open FD limit, etc. It's up to the library to report how the call failed, and up to the application to make a nice error report. The fact that the call failed should be obvious to the caller, because it called `memfd_create()`.

> In my experience as libraries expand, even if they are just a thin wrapper around some OS functionality, they inevitably gain new and exciting error cases that `io::Error` is not very good at accommodating.

I'm not convinced this is really true for low level wrappers. I can't think of anything more to do than calling `memfd_create()`. But even then, adding error variants will be a backwards incompatible change, so you might as well change the error type at that point.

> Another option I could see is using specific newtypes (enums with a single variant) over `io::Error` for each different function.

This would certainly be better than squashing them together in a single error type. However, I don't see any benefit in adding specific error types at this point. I think it would even complicate user code rather than simplify it. Consider the following:

```rust
fn do_stuff() -> Result<(), ()> {
  let fd = MemFdOptions::new().create("flooble-crank")
    .map_err(|e| log::error!("Failed to create memfd for flooble crank: {}", e))?;
  fd.as_file().set_len(2048)
    .map_err(|e| log::error!("Failed to allocate space for flooble crank: {}", e))?;

 ...
}
```

With the current error type or a similar error just for `create()`, it will log: `Failed to create memfd for fooblecrank: cannot create memfd`. If `create()` just return an `io::Error` it could log: `Failed to create memfd for fooblecrank: Too many open files (os error 24)`.

Of course, this can be solved with more complicated error reporting solutions too. But I still believe it is better to let the caller add context information about what the application was doing, and let the library just report how that operation failed.

**Comment by nagisa** [comment]
> memfd_create can fail in multiple ways

And that information is available via the source chain, isn't it?

> I can't think of anything more to do than calling memfd_create()

Various compatibility concerns tend to force hand one way or the other here.

> adding error variants will be a backwards incompatible change

I guess the original `Error` enum was not `#[non_exhaustive]` but making enums non-exhaustive would make adding variants backwards compatible.

**Comment by de-vri-es** [comment]
> > memfd_create can fail in multiple ways
> 
> And that information is available via the source chain, isn't it?

Yes, but that adds unnecessary complexity to get to the actual error details. I don't see any value in telling the caller of `create()` that it was creating the memfd that failed. The caller really should already know that.

> > adding error variants will be a backwards incompatible change
> 
> I guess the original `Error` enum was not `#[non_exhaustive]` but making enums non-exhaustive would make adding variants backwards compatible.

I don't think that breaking backwards compatibility is a bad thing here. If you care enough about the error details to handle specific variants differently, I would want my code to stop compiling when a variant is added. And cargo will ensure no applications or libraries break automatically.

> > I can't think of anything more to do than calling memfd_create()
> 
> Various compatibility concerns tend to force hand one way or the other here.

There aren't currently any such incompatibilities. All I can foresee is different platforms defining incompatible traits in the future, but those can be represented by `io::Error` just fine. And if something awful happens that does warrant a new error variant, I don't see an issue with breaking backwards compatibility with a proper version bump.

Above all: I really don't see a reason to deviate from the way `std` does things here. It doesn't have separate `io::OpenError`, `io::ReadError`, `io::WriteError`, etc. Why should `memfd`? It just means the user has to know more details about the error type to know which additional context to add and which is already added by the error type.

**Comment by nagisa** [comment]
> With the current error type or a similar error just for create(), it will log: `Failed to create memfd for fooblecrank: cannot create memfd`. If create() just return an io::Error it could log: `Failed to create memfd for fooblecrank: Too many open files (os error 24).`

This could be mitigated by forwarding the display implementation (much like `thiserorr`'s `#[error(transparent)]` does), without necessarily entirely dropping the enum usage.

---

I guess I don't care too strongly either way, giving time for @lucab to express their opinion.

**Comment by de-vri-es** [comment]
> This could be mitigated by forwarding the display implementation (much like `thiserorr`'s `#[error(transparent)]` does), without necessarily entirely dropping the enum usage.

Wouldn't that duplicate information if you do show the whole error chain though? Or should it also report `None` in `source()` then?

> I guess I don't care too strongly either way, giving time for @lucab to express their opinion.

Righty :)

**Comment by nagisa** [comment]
> Or should it also report None in source() then?

It would forward to contained type's `source` as well.

**Comment by de-vri-es** [comment]
> It would forward to contained type's `source` as well.

Right, that makes sense.

**Comment by lucab** [comment]
Unfortunately I don't have a good answer here. The approach I took here initially was this one https://docs.rs/memfd/0.1.0/memfd/errors/enum.ErrorKind.html, but I'm not very fond of that. I'm not a fan of piggy-backing on `io::Error`, but neither I like a sprawl of error types.

In practice in consumer applications I rarely found myself in need of pattern matching all error kinds.
Also, this isn't the case here, but I've been bitten way too many times by chains of foreign error types and version mismatches.

Thus, lately I started appreciating opaque error structs with optional getters only for specific cases (e.g. `struct OpaqueError {...}` and `fn OpaqueError::os_error(&self) -> Option<std::io::Error>`).
Up to your consideration. In general I feel a library error type, structured whatver way you prefer, is better than the plain `std::io::Error`.

**Comment by de-vri-es** [comment]
Alright, one last attempt :p

In essence, `memfd` is really just a few syscall wrappers (very useful wrappers, mind). To my mind, `std::io::Error` is the standard way of reporting OS errors (especially from tiny syscall wrappers).

There is one additional operation in `memfd` that isn't just forwarding to a syscall: converting the name to a null-terminated C-string. But that has precedence in `std` too: it is also reported as `std::io::Error`.

So why not just return `std::io::Error`? Custom error types really feel like unnecessary complexity here, both in the implementation and for the users of the crate.

If I can't sway you both, I can convert the PR to separate error types per call. I'd prefer to stick with `std::io::Error` though :)

**Comment by lucab** [comment]
I'm doing some spring cleaning today, and I think this PR failed to reach consensus.
While I understand the motivations and appreciate @de-vri-es feedback, there are (as always) tradeoffs at hand. Reading through the whole thread I don't see a clear winner over the current status quo.
I'm closing this PR for now, but I'm open to moving the error handling in any direction which isn't the plain `std:io::Error`, as I agree with the very first feedback from @nagisa on that.

**Pull request closed without merging**
