### PR TITLE
Move to github actions

### PR DESCRIPTION
**Pull request by nagisa**

### CODE REVIEW

**Comment by nagisa** [comment]
@lucab can you remove the travis from required checks?

**Comment by lucab** [comment]
@nagisa done. To replace that, which other actions should be marked as required?

**Comment by nagisa** [comment]
Probably just `native-test (stable)`, if anything at all.

**Comment by lucab** [comment]
Ack, I've enabled that one as a safety net. PR LGTM.
I'll go ahead and disable Travis entirely, unless you have some other plans for it.

**Review by lucab — APPROVED** [review]

**Pull request merged**
