### PR TITLE
FreeBSD support

### LINKED ISSUE #13: FreeBSD support
FreeBSD [has a compatibility layer for `memfd_create`](https://github.com/freebsd/freebsd/commit/575e351fdd996f72921b87e71c2c26466e887ed2) but we are calling a syscall directly, thus failing to work on FreeBSD. Should make ourselves compatible with FreeBSD (and CI it)

### PR DESCRIPTION
**Pull request by nagisa**
Fixes #13

### CODE REVIEW

**Comment by nagisa** [comment]
Needs https://github.com/rust-lang/libc/pull/1810 before passes.

**Comment by lucab** [comment]
@nagisa it looks like you PR landed in `libc` 0.2.71. Let's tweak the cargo manifest accordingly and land this.

**Comment by nagisa** [comment]
So this won't work in CI as is, because the `build.rs` of `libc` tries to detect the version of freebsd used. Since we cross-build it defaults to freebsd11.0, while the wrappers for the APIs used are only available in freebsd13.0, making he CI fail.

**Comment by lucab** [comment]
@nagisa really crude hack, but perhaps dropping a `/usr/bin/freebsd-version` script in the GH runner with a bare `echo 13` could make it work?

**Comment by nagisa** [comment]
Yeah, that's exactly what I'm trying to hack in right now. I think that'll be good enough for us.

**Comment by nagisa** [comment]
Huh, so even if we _do_ add the `freebsd-version`, `libc` also checks for `LIBC_CI` environment variable:

https://github.com/rust-lang/libc/blob/5f7c6c1ef93ff4fcfa3d767aac93c2b261c8f140/build.rs#L12
https://github.com/rust-lang/libc/blob/5f7c6c1ef93ff4fcfa3d767aac93c2b261c8f140/build.rs#L26-L34

So I think ultimately this is blocked on libc doing something different about its feature detection. Probably blocked for quite a while.

**Comment by nagisa** [comment]
Closing this for now.

**Comment by vishwin** [comment]
Can this development be restarted? FreeBSD 13 branch, when `memfd_create` was added, is about to go EOL, so all supported versions including -CURRENT have this. It would greatly help with porting later versions of flare, which uses glycin, which uses memfds.

**Comment by vishwin** [comment]
Had a crack at this on FreeBSD 16-CURRENT: only the `src/lib.rs` changes are needed after the refactor to `rustix`. All tests pass.

**Comment by nagisa** [comment]
Cool, send a PR.

**Pull request closed without merging**
